### ISSUE TITLE
Difference to revolsys/kong-plugin-upstream-auth-basic?

### ISSUE THREAD

**Issue by konradkonrad** [mvanholsteijn/kong-plugin-upstream-basic-auth#2]
This is really confusing. Could you expand on when a user (me) wants to use your plugin instead of https://github.com/revolsys/kong-plugin-upstream-auth-basic ?

See also: https://github.com/revolsys/kong-plugin-upstream-auth-basic/issues/3

**Comment by mvanholsteijn** [comment]
This plugin takes the username and password from the credentials stored with the consumer.  The revolsys plugin specifies the username and password as a property of the plugin. 

So if you want to forward to a backend service which requires a fixed username and password, than the revolsys plugin is better suited.  If your backend service requires basic auth and requires that each caller is identified at the backend, this one would probably be more suited.

**Comment by konradkonrad** [comment]
thank you very much!
